language: node_js
node_js:
- '12'
- '14'
deploy:
  provider: script
  script: 'echo "//registry.npmjs.org/:_authToken=${API_TOKEN}" > $HOME/.npmrc && npm publish --access=public'
  on:
    tags: true
    condition: $TRAVIS_NODE_VERSION = 12
  skip_cleanup: true

notifications:
  email: false
